; Bell Labs PDP-11/20, late summer 1970
; Processor has arrived; disk has not.

set cpu 11/20
set cpu 24K
set cpu history=100
set cpu noidle

; Keep only the console terminal for now.
; Other hardware will be added when we have historical evidence
; or when the surviving transition software requires it.

set rha disa
set clk disa
set ptr ena
set ptp disa
set lpt disa
set dz disa

set rk disa
set rl disa
set hk disa
set rx disa
set rp disa
set rq disa

set tm disa
set tq disa

set rom disa

show cpu
show dev
show ptr
